#!/usr/bin/env python
## Controller Config
STIFFNESS_ROT_HIGH = 30
STIFFNESS_ROT_LOW =  0
DAMPING_ROT_HIGH = 14
DAMPING_ROT_LOW = 0
STIFFNESS_LIN_HIGH = 150
STIFFNESS_LIN_LOW = 0
DAMPING_LIN_HIGH = 90
DAMPING_LIN_LOW = 0
## Particle Filter Config
RESAMPLE_PROPORTION_HIGH = 0.042
RESAMPLE_PROPORTION_LOW = 0.0
NOISE_XY_HIGH = 0.06# 0.03 works well
NOISE_XY_LOW = 0.001 # 0.005 works well
NOISE_THETA_HIGH = 0.16
NOISE_THETA_LOW = 0.003

